In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


demo_df = pd.DataFrame({'Categorical Feature': ['socks', 'fox', 'socks', 'box'],
                        'Integer feature': [0,1,2,1]})
display(demo_df)

  Categorical Feature  Integer feature
0               socks                0
1                 fox                1
2               socks                2
3                 box                1

In [7]:
display(pd.get_dummies(demo_df))

,Integer feature,Categorical Feature_box,Categorical Feature_fox,Categorical Feature_socks
0,0,False,False,True
1,1,False,True,False
2,2,False,False,True
3,1,True,False,False

In [13]:
## Recent updates to the pandas library changed the default output of pd.get_dummies() to booleans (True/False) instead of integers (1/0).To force the function to return 1 and 0, simply add the dtype=int parameter to your code:
# New Code with dtype=int or dtype=float

display(pd.get_dummies((demo_df),dtype= float))

,Integer feature,Categorical Feature_box,Categorical Feature_fox,Categorical Feature_socks
0,0,0.0,0.0,1.0
1,1,0.0,1.0,0.0
2,2,0.0,0.0,1.0
3,1,1.0,0.0,0.0

In [ ]:
"""BINNING, DISECRATION, LINEAR MODELS AND TREES"""

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor